### ISSUE TITLE
[Feature] Add support for /status/kafka-details request

### ISSUE THREAD

**Issue by rbardaji** [sci-ndp/pop-py#12]
The `APIClient` needs to support making a request to the `/status/kafka-details` endpoint, available in version 0.3.0 of the API. This functionality should allow users to fetch Kafka connection details (`host`, `port`, and `connection status`) programmatically through the library.

#### Requirements:
1. Create a new method (e.g., `get_kafka_details`) in the appropriate class/module.
2. Use the `APIClientBase` class to perform the request to `/status/kafka-details`.
3. Handle errors gracefully and return a clear response to the user if the API is unavailable or returns an error.
4. Include unit tests to validate the functionality.

#### API Endpoint:
- **Endpoint:** `/status/kafka-details`
- **Method:** `GET`
- **Response Example:**
  ```json
  {
      "kafka_host": "localhost",
      "kafka_port": 9092,
      "kafka_connection": true
  }
  ```

#### Tasks:
- [x] Implement the new method in the appropriate class/module.
- [x] Add error handling for network or API issues.
- [x] Write unit tests to cover success and failure scenarios.
- [x] Update documentation to include the new method.

#### Additional Notes:
- Ensure compatibility with existing authentication mechanisms (token or username/password).

**Comment by rbardaji** [comment]
Done in #13
